# Generated by Django 3.1.4 on 2021-06-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Billing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Billing_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Plan_Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Plan_Cost', models.CharField(blank=True, max_length=100, null=True)),
                ('Total', models.CharField(blank=True, max_length=100, null=True)),
                ('Invoice_id', models.CharField(blank=True, max_length=500, null=True)),
                ('Quantity', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('Invoice_date', models.DateField()),
                ('Due_date', models.DateField()),
                ('Payment_mode', models.CharField(blank=True, max_length=500, null=True)),
                ('Bill_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('Ref_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('Paid_date', models.DateField()),
                ('Paid_amt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
