# Generated by Django 3.1.4 on 2021-06-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('Ref_no', models.CharField(blank=True, default='Ref_16325', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormD',
            fields=[
                ('Billing_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Billing_Address', models.CharField(blank=True, max_length=500, null=True)),
                ('Plan_Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Plan_Cost', models.CharField(blank=True, max_length=100, null=True)),
                ('Total', models.CharField(blank=True, max_length=100, null=True)),
                ('Invoice_id', models.UUIDField(default='inv_e45e5465-f', primary_key=True, serialize=False, unique=True)),
                ('Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('Invoice_date', models.DateTimeField()),
                ('Due_date', models.DateTimeField()),
                ('Payment_mode', models.CharField(blank=True, max_length=500, null=True)),
                ('Bill_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('Ref_no', models.CharField(blank=True, max_length=1000, null=True)),
                ('Paid_date', models.DateTimeField()),
                ('Paid_amt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
