# Generated by Django 3.1.4 on 2021-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formd',
            name='Due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='formd',
            name='Invoice_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='formd',
            name='Paid_date',
            field=models.DateTimeField(),
        ),
    ]
