# Generated by Django 3.1.4 on 2021-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210611_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='formd',
            name='Mobile_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
