# Generated by Django 3.1.4 on 2021-08-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_formd_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='formd',
            name='Installation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
