# Generated by Django 3.1.4 on 2021-08-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_formd_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formd',
            name='Grand_total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
